### ISSUE TITLE
Unable to init kine client

### ISSUE THREAD

**Issue by manoj2378** [mapbox/kine#20]
Hi,
I am initializing a kine client using the following code.

var Kine = require("kine");
kine2 = Kine({
  streamName: 'test-stream',
  region: 'us-east-1',
  shardIteratorType: 'TRIM_HORIZON',
  table: 'teststreamdyno',
  accessKeyId: 'AccessKey',
  secretAccessKey:'SecretAccessKey',
  init: function(done) {
    console.log(this.id);
    done();
  },
  processRecords: function(records, done) {
    console.log(records);
    console.log(this.id);
     done(null, true);
  }
});

This is the Error Output:
/home/manoj/kinesis/kine/node_modules/dyno/node_modules/aws-sdk/lib/request.js:32
          throw err;
                ^
TypeError: Cannot read property 'length' of undefined
    at instancePosition (/home/manoj/kinesis/kine/lib/kcl.js:56:36)
    at shards (/home/manoj/kinesis/kine/lib/kcl.js:70:8)
    at /home/manoj/kinesis/kine/lib/kcl.js:46:7
    at notify (/home/manoj/kinesis/kine/node_modules/queue-async/build/queue.js:61:26)
    at abort (/home/manoj/kinesis/kine/node_modules/queue-async/build/queue.js:57:7)
    at /home/manoj/kinesis/kine/node_modules/queue-async/build/queue.js:45:11
    at /home/manoj/kinesis/kine/node_modules/dyno/lib/item.js:86:29
    at Response.response (/home/manoj/kinesis/kine/node_modules/dyno/lib/dynamoRequest.js:98:33)
    at Request.<anonymous> (/home/manoj/kinesis/kine/node_modules/dyno/node_modules/aws-sdk/lib/request.js:350:18)
    at Request.callListeners (/home/manoj/kinesis/kine/node_modules/dyno/node_modules/aws-sdk/lib/sequential_executor.js:100:18)

**Comment by mtfranchetto** [comment]
Hi @manoj2378, have you found a solution for this problem?

**Comment by tardunge** [comment]
no.
